default:
  emulator:
  core:
  options:
    videomode:      default
    ratio:          auto
    video_threaded: false
    smooth:         true
    rewind:         false
    bezel:          default
    forceNoBezel:   true

switch:
  emulator: eden-emu
  core:     eden-emu
  options:
    bezel: none
    forceNoBezel: true
    hud_support: true